#!/bin/bash
#==========================================
# Copyright © 2020 Intel Corporation
#
# SPDX-License-Identifier: MIT
#==========================================
# Script to submit job in Intel(R) DevCloud
# Version: 0.7
#==========================================


if [ -z "$1" ] || [ -z "$2" ]; then
    echo "Missing script argument, Usages:"
    echo "./q launch.sh <bin_file> "
    echo "./q run.sh <bin_file> <num_nodes>"
    echo ""
elif [ ! -f "$1" ]; then
    echo "File $1 does not exist"
else
    if [ -z "$3" ]; then
        nodestring="nodes=1:ppn=2"
    else
        nodestring=$3
    fi
    
    echo "Job <$2> has been submitted to Intel(R) DevCloud with $num_nodes nodes and will execute soon."

    echo ""
    
    echo " If you do not see result in 60 seconds, please restart the Jupyter kernel:"
    echo " Kernel -> 'Restart Kernel and Clear All Outputs...' and then try again"
    echo ""
    script=$1
    file=$2
    # Remove old output files
    rm *.sh.* > /dev/null 2>&1
    # Submit job using qsub
    qsub_id=`qsub -l $nodestring -d . $script -F $file`
    
    job_id="$(cut -d'.' -f1 <<<"$qsub_id")"
    # Print qstat output
    qstat 
    # Wait for output file to be generated and display
    echo ""
    echo -ne "Waiting for Output "
    until [ -f $script.o$job_id ]; do
        sleep 1
        echo -ne "█"
        ((timeout++))
        # Timeout if no output file generated within 60 seconds
        if [ $timeout == 60 ]; then
            echo ""
            echo ""
            echo "TimeOut 60 seconds: Job is still queued for execution, check for output file later ($script.o$job_id)"
            echo ""
            break
        fi
    done
    # Print output and error file content if exist
    if [ -n "$(find -name '*.sh.o'$job_id)" ]; then
        echo " Done⬇"
        cat $script.o$job_id
        cat $script.e$job_id
        echo "Job Completed in $timeout seconds."
        rm *.sh.*$job_id > /dev/null 2>&1        
    fi
fi
